services:
  mariadb:
    image: mariadb:latest
    container_name: carreb_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: S3cretP4ssw0rd!
      MYSQL_DATABASE: carreb_db
      MYSQL_USER: carreb_usr
      MYSQL_PASSWORD: P4ssw0rd!
    ports:
      - "33077:3306"
    expose:
      - 33077
    volumes:
      - ./mariadb_data:/var/lib/mysql  # Persistent data storage
      #- ./init-scripts:/docker-entrypoint-initdb.d  # Optional custom scripts

networks:
  backend_network:
    driver: bridge
    
volumes:
  mariadb_data: