# Generated by Django 4.2.20 on 2025-03-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carmake',
            table='car_make',
        ),
    ]
