# Generated by Django 4.2.20 on 2025-03-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_carmake_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('car_make_id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=23)),
                ('family', models.CharField(max_length=25)),
                ('variant', models.CharField(max_length=31)),
                ('series', models.CharField(max_length=23)),
                ('style', models.CharField(max_length=23)),
                ('engine', models.CharField(max_length=25)),
                ('cc', models.CharField(max_length=5)),
                ('size', models.CharField(max_length=6)),
                ('transmission', models.CharField(max_length=21)),
                ('cylinder', models.CharField(max_length=5)),
                ('width', models.CharField(max_length=6)),
                ('year', models.CharField(max_length=5)),
                ('month', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'car_detail',
            },
        ),
    ]
