# Generated by Django 4.2.20 on 2025-03-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cardetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardetail',
            old_name='car_make_id',
            new_name='car_model_id',
        ),
    ]
