# Generated by Django 4.2.20 on 2025-03-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_car_make_id_cardetail_car_model_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'state',
            },
        ),
    ]
