# Generated by Django 4.2.20 on 2025-04-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
