# Generated by Django 4.2.20 on 2025-05-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vehicle_vehicle_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarDetail',
            new_name='CarDetails',
        ),
        migrations.RenameModel(
            old_name='CarMake',
            new_name='CarMakes',
        ),
        migrations.RenameModel(
            old_name='State',
            new_name='States',
        ),
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='Vehicles',
        ),
        migrations.AlterModelTable(
            name='cardetails',
            table='car_details',
        ),
        migrations.AlterModelTable(
            name='carmakes',
            table='car_makes',
        ),
        migrations.AlterModelTable(
            name='states',
            table='states',
        ),
        migrations.AlterModelTable(
            name='vehicles',
            table='vehicles',
        ),
    ]
