# Generated by Django 4.2.20 on 2025-05-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_vehicles_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSearchLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('save_money', models.BooleanField(default=False)),
                ('greener_car', models.BooleanField(default=False)),
                ('good_all_rounder', models.BooleanField(default=False)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(blank=True, max_length=5, null=True)),
                ('have_car', models.BooleanField(default=False)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('referral_code', models.CharField(blank=True, max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'car_search_logs',
            },
        ),
    ]
