# Generated by Django 4.2.20 on 2025-05-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_carsearchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsearchlog',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
