# Generated by Django 4.2.20 on 2025-05-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_carsearchlog_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_id', models.CharField(blank=True, max_length=20, null=True)),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vehicle_images',
            },
        ),
    ]
