# Generated by Django 4.2.20 on 2025-05-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_vehicle_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle_Images',
            new_name='VehicleImages',
        ),
    ]
