# Generated by Django 4.2.21 on 2025-05-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_vehicle_images_vehicleimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='image_name',
        ),
        migrations.AddField(
            model_name='carsearchlog',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
