# Generated by Django 4.2.21 on 2025-06-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_vehicle_images_vehicleimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGarage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('save_money', models.BooleanField(default=False)),
                ('greener_car', models.BooleanField(default=False)),
                ('good_all_rounder', models.BooleanField(default=False)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(blank=True, max_length=5, null=True)),
                ('have_car', models.BooleanField(default=False)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_id', models.CharField(blank=True, max_length=20, null=True)),
                ('original_search_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('is_current_car', models.BooleanField(default=False)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'my_garage',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('payment_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('search_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('plan_name', models.CharField(max_length=100)),
                ('subscription_status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_subscriptions',
            },
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='image_name',
        ),
        migrations.AddField(
            model_name='carsearchlog',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
