# Generated by Django 4.2.21 on 2025-06-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_popular_carmakes_is_popular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmakes',
            old_name='active',
            new_name='is_active',
        ),
    ]
