# Generated by Django 4.2.21 on 2025-06-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_active_carmakes_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvariants',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='carvariants',
            name='sub_variant',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
