# Generated by Django 4.2.21 on 2025-06-14 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_carvariants_is_active_carvariants_sub_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carvariants',
            unique_together=set(),
        ),
    ]
