# Generated by Django 4.2.21 on 2025-06-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_cardataraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardataraw',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
