# Generated by Django 4.2.21 on 2025-06-15 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_cardataraw_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
                ('vehicle_class', models.CharField(blank=True, max_length=100, null=True)),
                ('grok_raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'car_models',
            },
        ),
        migrations.AddField(
            model_name='cardataraw',
            name='vehicle_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
