# Generated by Django 4.2.21 on 2025-06-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_carmodels_cardataraw_vehicle_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvariants',
            name='battery_capacity_kwh',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='carvariants',
            name='body_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carvariants',
            name='co2_emissions_combined_g_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='carvariants',
            name='drivetrain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carvariants',
            name='estimated_5yr_dealer_servicing_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='carvariants',
            name='estimated_5yr_resale_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='carvariants',
            name='fuel_efficiency_combined_l_100km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='carvariants',
            name='no_doors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carvariants',
            name='no_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carvariants',
            name='total_range_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
