# Generated by Django 4.2.21 on 2025-06-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_carvariants_battery_capacity_kwh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPricing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('car_variant_id', models.IntegerField(default=0)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('msrp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('drive_away_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('drive_away_price_with_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stamp_duty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('registration', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ctp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('govt_incentives', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dealer_delivery_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'car_pricing',
            },
        ),
    ]
