# Generated by Django 4.2.21 on 2025-06-19 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_carpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBodyCost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_cost_comprehensive_annual_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_cost_comprehensive_annual_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tyre_change_cost_per_tyre_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tyre_change_cost_per_tyre_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'car_body_cost',
            },
        ),
    ]
