# Generated by Django 4.2.21 on 2025-06-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_carbodycost'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvariants',
            name='fuel_capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
