# Generated by Django 4.2.21 on 2025-06-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_carvariants_fuel_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvariants',
            name='grok_json_fuel_battery_capacity',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
