# Generated by Django 4.2.21 on 2025-06-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_carvariants_grok_json_fuel_battery_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carvariants',
            name='grok_json_fuel_battery_capacity',
        ),
        migrations.AddField(
            model_name='carmakes',
            name='grok_json_fuel_battery_capacity',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
