# Generated by Django 4.2.21 on 2025-06-25 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_carvariants_grok_json_fuel_battery_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpricing',
            old_name='car_variant_id',
            new_name='variant_id',
        ),
        migrations.AddField(
            model_name='carpricing',
            name='car_variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.carvariants'),
        ),
    ]
