# Generated by Django 4.2.21 on 2025-06-25 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_car_variant_id_carpricing_variant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelRetailPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], default='petrol', max_length=10)),
                ('year_type', models.CharField(choices=[('cy', 'Calendar Year'), ('fy', 'Financial Year')], default='cy', max_length=2)),
                ('year_from', models.IntegerField(null=True)),
                ('year_to', models.IntegerField(null=True)),
                ('nsw', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vic', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qld', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('act', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('national', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'fuel_retail_price',
            },
        ),
    ]
