# Generated by Django 4.2.21 on 2025-06-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_fuelretailprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvariants',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
