# Generated by Django 4.2.21 on 2025-06-26 16:07

from django.db import migrations

def populate_grid_emissions(apps, schema_editor):
    """
    Populates the ElectricityGridEmissions table with data from the
    'Master Calculations Carreb v2 (5).xlsx - Electricity Emissions.csv' file.
    """
    ElectricityGridEmissions = apps.get_model('api', 'ElectricityGridEmissions')

    # Data from 'Master Calculations Carreb v2 (5).xlsx - Electricity Emissions.csv'
    emissions_data = {
        'NSW': 0.79,
        'VIC': 0.85,
        'QLD': 0.73,
        'SA': 0.43,
        'WA': 0.64,
        'TAS': 0.13,
        'NT': 0.53,
        'ACT': 0.12,
    }

    for state, factor in emissions_data.items():
        ElectricityGridEmissions.objects.update_or_create(
            state=state,
            defaults={'emissions_factor_kg_per_kwh': factor}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_electricitygridemissions'),
    ]

    operations = [
        migrations.RunPython(populate_grid_emissions),
    ]